import {
  Sponsor,
  HeroSlide,
  Banner,
  SocialLink,
  WheelReward,
  StoreProduct,
  Giveaway,
  GiveawayTemplate,
  SiteSettings,
  Profile,
} from '../types';

export const initialSiteSettings: SiteSettings = {
  site_name: 'SHELBYONLINE',
  site_title: 'ShelbyOnline | Premium Sponsor & Kampanya Platformu',
  site_description:
    'Doğrulanmış güvenilir sponsor platformları, özel yatırım ve deneme bonusları, günlük çark hediyeleri ve ödüllü topluluk çekilişleri.',
  logo_text: 'SHELBYONLINE',
  logo_tagline: 'PREMIUM SPONSOR & GAMING NETWORK',
  footer_text:
    'ShelbyOnline, doğrulanmış eğlence ve sponsorluk ağlarının en güncel bonuslarını sunan bağımsız bir topluluk portalıdır. 18 yaşından küçüklerin katılımı yasaktır.',
  telegram_url: 'https://t.me/ShelbyOnline',
  telegram_channel_url: 'https://t.me/ShelbyOnline',
  telegram_chat_url: 'https://t.me/ShelbyOnline_Chat',
  telegram_bot_username: 'ShelbyOnlineBOT',
  telegram_bot_token: '8944054737:AAHD_G8mzXVQiYEQnqUDiLa6hSJyRdIyjeY',
  telegram_bot_url: 'https://t.me/ShelbyOnlineBOT',
  telegram_login_enabled: true,
  twitter_url: 'https://x.com/ShelbyOnline',
  instagram_url: 'https://instagram.com/ShelbyOnline',
  support_email: 'destek@shelbyonline.com',
  maintenance_mode: false,
  registration_enabled: true,
  // Top Announcement Banner
  announcement_enabled: true,
  announcement_text: '🔥 Yeni Sezon Çekilişi Başladı! Telegram ile giriş yapıp +250 Hoş Geldin Coini anında kapın!',
  announcement_link: '/giveaways',
  announcement_badge: 'YENİ ETKİNLİK',
  // Economy & Coins
  welcome_coin_bonus: 250,
  daily_wheel_free_spins: 1,
  streak_bonus_enabled: true,
  streak_rewards: [
    { day: 1, reward_coins: 50, label: '50 Coin' },
    { day: 2, reward_coins: 100, label: '100 Coin' },
    { day: 3, reward_coins: 150, label: '150 Coin' },
    { day: 4, reward_coins: 200, label: '200 Coin' },
    { day: 5, reward_coins: 300, label: '300 Coin' },
    { day: 6, reward_coins: 500, label: '500 Coin' },
    { day: 7, reward_coins: 1000, label: '1000 VIP + Sandık', vip: true },
  ],
  // Page Control Toggles
  page_sponsors_enabled: true,
  page_wheel_enabled: true,
  page_giveaways_enabled: true,
  page_leaderboard_enabled: true,
  page_store_enabled: true,
  page_games_enabled: true,
  page_live_enabled: true,
  page_about_enabled: true,
  page_contact_enabled: true,
  // Maintenance text
  maintenance_title: 'Sayfa Geçici Olarak Bakımdadır',
  maintenance_description: 'Yöneticilerimiz bu sayfayı güncelliyor. Lütfen kısa bir süre sonra tekrar ziyaret ediniz.',
};

export const initialProfiles: Profile[] = [];

export const initialSponsors: Sponsor[] = [];

export const initialHeroSlides: HeroSlide[] = [
  {
    id: 'slide-1',
    desktop_image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1400&h=500&q=80',
    mobile_image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&h=600&q=80',
    target_url: '/giveaways',
    sort_order: 1,
    active: true,
  },
  {
    id: 'slide-2',
    desktop_image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1400&h=500&q=80',
    mobile_image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&h=600&q=80',
    target_url: '/wheel',
    sort_order: 2,
    active: true,
  },
  {
    id: 'slide-3',
    desktop_image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1400&h=500&q=80',
    mobile_image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&h=600&q=80',
    target_url: '/store',
    sort_order: 3,
    active: true,
  },
];

export const initialBanners: Banner[] = [
  {
    id: 'ban-left',
    name: 'Marsbahis VIP Reklam',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&h=800&q=80',
    target_url: 'https://marsbahis.com',
    position: 'left',
    active: true,
    sort_order: 1,
    clicks_count: 1420,
  },
  {
    id: 'ban-right',
    name: 'Grandpashabet Reklam',
    image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=300&h=800&q=80',
    target_url: 'https://grandpashabet.com',
    position: 'right',
    active: true,
    sort_order: 2,
    clicks_count: 1280,
  },
];

export const initialSocialLinks: SocialLink[] = [
  {
    id: 'soc-1',
    platform: 'Telegram',
    title: 'Telegram Kanalı',
    subtitle: 'Giriş Kodu & Çekilişler',
    url: 'https://t.me/ShelbyOnline',
    icon: 'Send',
    active: true,
    sort_order: 1,
  },
  {
    id: 'soc-2',
    platform: 'Twitter',
    title: 'X / Twitter',
    subtitle: 'Anlık Duyurular & Kodlar',
    url: 'https://x.com/ShelbyOnline',
    icon: 'Twitter',
    active: true,
    sort_order: 2,
  },
  {
    id: 'soc-3',
    platform: 'Instagram',
    title: 'Instagram',
    subtitle: 'Ödüller & Hikayeler',
    url: 'https://instagram.com/ShelbyOnline',
    icon: 'Instagram',
    active: true,
    sort_order: 3,
  },
];

export const initialWheelRewards: WheelReward[] = [
  { id: 'rw-1', title: '250 Coin', reward_type: 'coin', reward_value: 250, probability: 25, color: '#8B5CF6', active: true, sort_order: 1 },
  { id: 'rw-2', title: '50 Coin', reward_type: 'coin', reward_value: 50, probability: 15, color: '#3B82F6', active: true, sort_order: 2 },
  { id: 'rw-3', title: '500 Coin', reward_type: 'coin', reward_value: 500, probability: 15, color: '#EC4899', active: true, sort_order: 3 },
  { id: 'rw-4', title: '150 Coin', reward_type: 'coin', reward_value: 150, probability: 10, color: '#10B981', active: true, sort_order: 4 },
  { id: 'rw-5', title: '100 Coin', reward_type: 'coin', reward_value: 100, probability: 20, color: '#F59E0B', active: true, sort_order: 5 },
  { id: 'rw-6', title: '1000 VIP Coin', reward_type: 'coin', reward_value: 1000, probability: 5, color: '#F43F5E', active: true, sort_order: 6 },
  { id: 'rw-7', title: '300 Coin', reward_type: 'coin', reward_value: 300, probability: 10, color: '#06B6D4', active: true, sort_order: 7 },
];

export const initialGiveaways: Giveaway[] = [
  {
    id: 'gw-1',
    title: 'iPhone 16 Pro Max Büyük Yaz Çekilişi',
    description: 'Topluluk üyelerimize özel dev hediye! Tek tıkla çekilişe katıl, kazanma şansını yakala.',
    prize_details: '1x Apple iPhone 16 Pro Max 256GB Titanyum',
    image_url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&h=450&q=80',
    start_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    end_at: new Date(Date.now() + 7 * 86400000).toISOString(),
    entries_count: 284,
    winner_count: 1,
    active: true,
    is_completed: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'gw-2',
    title: 'PlayStation 5 Slim & 50.000 TL Nakit Dağıtımı',
    description: 'Haftalık büyük oyun ve nakit paketi. Çekiliş sonuçları canlı olarak açıklanacaktır.',
    prize_details: '1x Sony PS5 Slim + 50.000 TL Nakit Ödül',
    image_url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&h=450&q=80',
    start_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    end_at: new Date(Date.now() + 5 * 86400000).toISOString(),
    entries_count: 412,
    winner_count: 3,
    active: true,
    is_completed: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'gw-3',
    title: '100.000 TL Topluluk Nakit Havuzu',
    description: 'Papara, Banka veya Kripto ile anında çekilebilir nakit ödül havuzu.',
    prize_details: '10x 10.000 TL Nakit Ödül',
    image_url: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&h=450&q=80',
    start_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    end_at: new Date(Date.now() + 9 * 86400000).toISOString(),
    entries_count: 538,
    winner_count: 10,
    active: true,
    is_completed: false,
    created_at: new Date().toISOString(),
  },
];

export const initialStoreProducts: StoreProduct[] = [
  {
    id: 'prod-1',
    name: '100 TL Steam Cüzdan Kodu',
    description: 'Tüm Steam oyunları ve pazar içi harcamalar için geçerli dijital kod.',
    coin_price: 1000,
    category: 'gift_card',
    image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&h=300&q=80',
    stock: 50,
    active: true,
    sort_order: 1,
  },
  {
    id: 'prod-2',
    name: '250 TL Sponsor Freebet Kodu',
    description: 'Seçili VIP sponsor platformlarında geçerli risksiz spor ve casino bakiyesi.',
    coin_price: 1500,
    category: 'game_code',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&h=300&q=80',
    stock: 30,
    active: true,
    sort_order: 2,
  },
  {
    id: 'prod-3',
    name: '1 Aylık Discord Nitro',
    description: 'Özel emojiler, süper tepkiler ve HD yayın imkanı sunan Nitro kodu.',
    coin_price: 1200,
    category: 'digital',
    image_url: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?auto=format&fit=crop&w=400&h=300&q=80',
    stock: 25,
    active: true,
    sort_order: 3,
  },
  {
    id: 'prod-4',
    name: '500 TL Razer Gold PIN',
    description: 'Yüzlerce mobil ve PC oyununda geçerli evrensel oyun bakiyesi.',
    coin_price: 3500,
    category: 'game_code',
    image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=400&h=300&q=80',
    stock: 20,
    active: true,
    sort_order: 4,
  },
  {
    id: 'prod-5',
    name: '1 Aylık Netflix Premium',
    description: 'Ultra HD 4K çözünürlükte kesintisiz dizi ve film izleme üyeliği.',
    coin_price: 2000,
    category: 'digital',
    image_url: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=400&h=300&q=80',
    stock: 15,
    active: true,
    sort_order: 5,
  },
  {
    id: 'prod-6',
    name: '3 Aylık Spotify Premium',
    description: 'Reklamsız ve çevrimdışı yüksek kaliteli müzik dinleme deneyimi.',
    coin_price: 1800,
    category: 'digital',
    image_url: 'https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?auto=format&fit=crop&w=400&h=300&q=80',
    stock: 40,
    active: true,
    sort_order: 6,
  },
];

export const initialGiveawayTemplates: GiveawayTemplate[] = [
  {
    id: 'tpl-ps5',
    name: '🎮 PS5 Paketi',
    title: 'Haftalık PlayStation 5 & Nakit Çekilişi',
    prize_details: '1x Sony PS5 Slim + 50.000 TL Nakit Ödül',
    image_url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&h=450&q=80',
    description: 'Topluluk üyelerimize özel dev çekiliş. Tek tıkla hemen katıl.',
    duration_days: 7,
    badge_color: 'violet',
  },
  {
    id: 'tpl-iphone',
    name: '📱 iPhone 16 Pro',
    title: 'iPhone 16 Pro Max Büyük Yaz Çekilişi',
    prize_details: '1x Apple iPhone 16 Pro Max 256GB Titanyum',
    image_url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&h=450&q=80',
    description: 'En son model iPhone 16 Pro Max hediyesi. Şansını kaçırma.',
    duration_days: 7,
    badge_color: 'rose',
  },
  {
    id: 'tpl-cash',
    name: '💰 100.000 TL Nakit',
    title: '100.000 TL Topluluk Nakit Dağıtımı',
    prize_details: '100.000 TL Nakit Ödül (Banka Havalesi / Papara / Kripto)',
    image_url: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&h=450&q=80',
    description: 'Her hafta dev nakit ödüller topluluğumuza dağıtılıyor.',
    duration_days: 5,
    badge_color: 'amber',
  },
];
